  version: '3.9'

  services:
    db:
      image: postgres:17
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: mydb
      ports:
        - "5432:5432"
      volumes:
        - open-adoption-db:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

    api:
      build:
        context: ./src
        dockerfile: ./cmd/rest/Dockerfile
      restart: always
      environment:
        JWT_SECRET_KEY: "43345349009"
        ISSUER: "questionnaire-api"
        EXPIRATION_TIME: "15"
        REFRESH_EXPIRATION_TIME: "60"
        DB_URL: postgres://postgres:postgres@db:5432/mydb?sslmode=disable
      ports:
        - "8080:8080"
      depends_on:
        - db

    migrate:
      image: migrate/migrate
      volumes:
        - ./src/migrations:/migrations:ro,Z
      environment:
        DB_URL: postgres://postgres:postgres@db:5432/mydb?sslmode=disable
      entrypoint: ["sh", "-c", "migrate -source=file://migrations -database '${DB_URL}' up"]
      depends_on:
        - db

  volumes:
    open-adoption-db:
