// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pet.sql

package querier

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adoptPetById = `-- name: AdoptPetById :exec
UPDATE pets.pets
SET is_adopted = TRUE
WHERE id = $1
`

func (q *Queries) AdoptPetById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, adoptPetById, id)
	return err
}

const createPet = `-- name: CreatePet :exec
INSERT INTO pets.pets (
    id, name, breed, age, gender, is_adopted
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreatePetParams struct {
	ID        uuid.UUID
	Name      string
	Breed     string
	Age       string
	Gender    PetGender
	IsAdopted bool
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) error {
	_, err := q.db.Exec(ctx, createPet,
		arg.ID,
		arg.Name,
		arg.Breed,
		arg.Age,
		arg.Gender,
		arg.IsAdopted,
	)
	return err
}

const getPetById = `-- name: GetPetById :one
SELECT id, name, breed, age, gender, is_adopted
FROM pets.pets
WHERE id = $1
`

func (q *Queries) GetPetById(ctx context.Context, id uuid.UUID) (PetsPet, error) {
	row := q.db.QueryRow(ctx, getPetById, id)
	var i PetsPet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Breed,
		&i.Age,
		&i.Gender,
		&i.IsAdopted,
	)
	return i, err
}

const listImagesById = `-- name: ListImagesById :many
SELECT url
FROM pets.pet_images
WHERE pet_id = $1
`

func (q *Queries) ListImagesById(ctx context.Context, petID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listImagesById, petID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPets = `-- name: ListPets :many
SELECT id, name, breed, age, gender, is_adopted
FROM pets.pets
ORDER BY name
`

func (q *Queries) ListPets(ctx context.Context) ([]PetsPet, error) {
	rows, err := q.db.Query(ctx, listPets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PetsPet
	for rows.Next() {
		var i PetsPet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Breed,
			&i.Age,
			&i.Gender,
			&i.IsAdopted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePet = `-- name: UpdatePet :exec
UPDATE pets.pets
SET name = $2,
    breed = $3,
    age = $4,
    gender = $5
WHERE id = $1
`

type UpdatePetParams struct {
	ID     uuid.UUID
	Name   string
	Breed  string
	Age    string
	Gender PetGender
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) error {
	_, err := q.db.Exec(ctx, updatePet,
		arg.ID,
		arg.Name,
		arg.Breed,
		arg.Age,
		arg.Gender,
	)
	return err
}
